seed: 42

huggingface:
  hf_token: ""

model:
  name: "Qwen/Qwen2.5-7B-Instruct"
  use_huggingface_self_trained_model: false
  merge_lora: false
  save_merged_model_path: ""
  checkpoint_path: ""
  multi_gpu: false
  max_seq_length: 1024
  use_vllm: true
  vllm_kwargs:
    gpu_memory_utilization: 0.9
    tensor_parallel_size: 1
    dtype: "bfloat16"
    enforce_eager: false
    max_model_len: 1024

dataset:
  kg_name: "yago3-10"

finetune:
  use_lora: true                   # Whether to use LoRA for finetuning (true for LoRA, false for standard finetuning)
  use_qlora: false

utility:
  run_normal: true
  sample_size: 2000       # number of non-target triples to test utility
  loc: true               # true for local triples, false for global triples
  loc_num: 3              # hop distance to define local triples
  batch_size: 500         # batch size for vllm prompt generation


  run_mmlu: false
  run_bbh: false
  run_triviaqa: false
  run_truthfulqa: false
  run_fluency: false
  utility_dataset_dir: ""
  targets: [
    '1_Stephen_King', '2_Confucius', '3_Bruce_Lee', '4_Warren_Buffett', '5_Christina_Aguilera',
    '6_Cindy_Crawford', '7_Marie_Osmond', '8_Paris_Hilton', '9_Justin_Bieber', '10_Prince_Harry,_Duke_of_Sussex',
    '11_Miley_Cyrus', '12_Genghis_Khan', '13_Liza_Minnelli', '14_Taylor_Swift', '15_Mark_Cuban',
    '16_Rhea_Perlman', '17_Mark_Hamill', '18_John_D._Rockefeller', '19_Alanis_Morissette', '20_Marlon_Brando',
    '21_50_Cent', '22_Jim_Morrison', '23_Evel_Knievel', '24_Beyoncé', '25_Reba_McEntire',
    '26_Justin_Timberlake', '27_Vanna_White', '28_Lil_Wayne', '29_Anna_Nicole_Smith', '30_Henry_Winkler',
    '31_Leonardo_da_Vinci', '32_Kanye_West', '33_Paul_Walker', '34_Daniel_Day-Lewis', '35_Jim_Parsons',
    '36_Henry_Kissinger', '37_Chuck_Norris', '38_Steven_Seagal', '39_Linda_Hamilton', '40_Danny_Trejo',
    '41_Sam_Elliott', '42_Michael_Strahan', '43_Paul_Simon', '44_Meghan,_Duchess_of_Sussex', '45_Bruce_Springsteen',
    '46_Raquel_Welch', '47_Lenny_Kravitz', '48_Bob_Saget', '49_Jon_Voight', '50_Ryan_Seacrest',
    '51_Betty_White', '52_Chris_Brown', '53_Travis_Kelce', '54_Jay-Z', '55_Jackie_Chan',
    '56_Mark_Harmon', '57_Whitney_Houston', '58_Rihanna', '59_Anderson_Cooper', '60_Brendan_Fraser',
    '61_Tim_Burton', '62_Serena_Williams', '63_Dionne_Warwick', '64_Michelle_Pfeiffer', '65_Selena_Gomez',
    '66_Kris_Jenner', '67_Hugh_Laurie', '68_Tom_Clancy', '69_John_Candy', '70_Vin_Diesel',
    '71_Dakota_Fanning', '72_R._Kelly', '73_Emilio_Estevez', '74_Socrates', '75_Brooke_Shields',
    '76_Bob_Barker', '77_Val_Kilmer', '78_Jennifer_Lopez', '79_Pamela_Anderson', '80_Tony_Blair',
    '81_Vincent_van_Gogh', '82_Lindsay_Lohan', '83_Rebel_Wilson', '84_Nicolas_Cage', '85_Ted_Danson',
    '86_John_Travolta', '87_Robert_Downey_Jr.', '88_Jason_Bateman', '89_Samuel_L._Jackson', '90_Karl_Marx',
    '91_Halle_Berry', '92_Larry_Bird', '93_Johnny_Cash', '94_Chevy_Chase', '95_Bill_Paxton',
    '96_Ice_Cube', '97_Don_Johnson', '98_Dwayne_Johnson', '99_RuPaul', '100_Matthew_Perry']

unlearn:
  unlearn_method: "no_unlearn_qwen" # Unlearning method
  checkpoint_name: "no_unlearn_qwen"

output:
  score_dir: ""